apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: iww17xgau-go 
  janus-idp.io/tekton: iww17xgau-go
  backstage.io/kubernetes-id: iww17xgau-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: iww17xgau-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml