apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iww17xgau-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iww17xgau-go 
  name: iww17xgau-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: iww17xgau-go 
